version: "3.7"
services:
    postgres-phen:
        container_name: postgres-phen
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-postgres
        image: postgresimage-phen
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - WEBCLIENT_PW=${WEBCLIENT_PW}
        volumes:
            - db-phen:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    app-phen:
        container_name: app-phen
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-flask
        image: flaskimage-phen
        env_file:
            - .env
        environment:
            - FLASK_ENV=prod
            - POSTGRES_USER=webclient
            - WEBCLIENT_PW=${WEBCLIENT_PW}
            - POSTGRES_DB=${POSTGRES_DB}
            - SECRET_KEY=${SECRET_KEY}
        # volumes:
        #   - flask-phen:/var/www/apache-flask/api
        volumes:
            - ./api:/var/www/apache-flask/api
        ports:
            - "80:80"
        tty: true
        depends_on:
            - postgres-phen
        entrypoint:
            - /var/www/apache-flask/scripts/docker_script.sh

    gdal-phen:
        container_name: gdal-phen
        restart: always
        image: gdal-phen
        build:
            context: .
            dockerfile: Dockerfile-gdal
        env_file:
            - .env
        volumes:
            - ./python:/python
        tty: true
        depends_on:
            - postgres-phen

volumes:
    db-phen:
        name: db-phen
# gb && cp -r public/static/ ../api/static ; cp -r public/* ../api/static ; cd ..
# docker exec -t postgres-phen pg_dump -c -U postgres phen > "/c/Users/fd7/OneDrive - Oak Ridge National Laboratory/phen_files/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql"
#ssh forest_carter@35.193.138.139 "pg_dump -c -d ndvidv2" >> ndvidv2.sql
