############################################################
# Dockerfile to build Flask App
# Based on
############################################################

# Set the base image
FROM python:3.7

# File Author / Maintainer
MAINTAINER Carlos Tighe

RUN apt-get update && apt-get install -y apache2 \
    libapache2-mod-wsgi \
    build-essential \
    vim \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

COPY ./apache/apache-flask.wsgi /var/www/apache-flask/
COPY ./apache/apache-flask.conf /etc/apache2/sites-available/
RUN a2ensite apache-flask
RUN a2enmod headers

COPY ./api /var/www/apache-flask/api/
COPY ./scripts /var/www/apache-flask/scripts

# Copy over and install the requirements
COPY ./manage.py /var/www/apache-flask/manage.py
RUN pip install -r /var/www/apache-flask/api/requirements.txt

RUN a2dissite 000-default.conf
RUN a2ensite apache-flask.conf

EXPOSE 80

WORKDIR /var/www/apache-flask
# COPY ./gatsby/public/ api/static/
# COPY ./gatsby/public/static api/static/
# CMD ["/bin/bash"]
CMD  /usr/sbin/apache2ctl -D FOREGROUND
# The commands below get apache running but there are issues accessing it online
# The port is only available if you go to another port first
# ENTRYPOINT ["/sbin/init"]
# CMD ["/usr/sbin/apache2ctl"]